config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'news#index'
  resources :news
end

app/models/new.rb
#
class New < ActiveRecord::Base
  validates :title,       presence: true
  validates :image,       presence: true
  validates :description, presence: true
  validates :content,     presence: true

  mount_uploader :image, NewsUploader
end

app/models/user.rb
#
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
#
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do
    render json: { error: 'Not found.', code: 404 }, status: :not_found
  end

  rescue_from ActionController::ParameterMissing do |e|
    render json: { error: e.message, code: :unprocessable_entity },
           status: :unprocessable_entity
  end
end

app/controllers/news_controller.rb
# News
class NewsController < ApplicationController
  before_action :set_new, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy,
                                            :new, :create]
  # GET /news
  # GET /news.json
  def index
    @news = New.all.reverse_order
    respond_to do |format|
      format.html
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @new }
    end
  end

  # GET /news/new
  def new
    @new = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @new = New.new(new_params)

    respond_to do |format|
      if @new.save
        format.html do
          redirect_to @new, notice: 'News was successfully created.'
        end
        format.json do
          render :show, status: :created, location: @new
        end
      else
        format.html do
          render :new
        end
        format.json do
          render json: @new.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @new.update(new_params)
        format.html do
          redirect_to @new, notice: 'L\'actualite à correctement été modifié.'
        end
        format.json do
          render :show, status: :ok, location: @new
        end
      else
        format.html do
          redirect_to edit_news_path(@new),
                      alert: 'Erreur lors de l\'édition de l\'actualite'
        end
        format.json do
          render json: @new.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @new.destroy
    respond_to do |format|
      format.html do
        redirect_to news_index_path,
                    notice: 'News was successfully destroyed.'
      end
      format.json do
        head :no_content
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_new
    @new = New.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  def new_params
    params.require(:new).permit(:title, :image, :description, :content)
  end
end

app/helpers/application_helper.rb
#
module ApplicationHelper
end

app/helpers/devise_helper.rb
#
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    full_messages = resource.errors.full_messages
    messages = full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Modevos", root_path , class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "News", news_index_path %></li>
            <li><a href="#">Agenda</a></li>
            <li><a href="#">Forum</a></li>
            <% if user_signed_in? %>
              <li><%= link_to "Disconnect", destroy_user_session_path,
                                            method: :delete %></li>
            <% else %>
              <li><%= link_to "Connexion", new_user_session_path %></li>
              <li><%= link_to "Inscription", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_social_bar.erb
<div class="col-md-3">
  <div class="row">
    <div class="col-md-12 col-sm-6">
      <a href="https://www.facebook.com/ModevosProduction" target="_blanck">
        <%= image_tag "social/facebook.png", alt: "Facebook",
                                             class: "mod-image" %>
      </a>
      <br><br>
    </div>
    <div class="col-md-12 col-sm-6">
      <a href="https://www.youtube.com/user/Modevos" target="_blanck">
        <%= image_tag "social/youtube.png", alt: "Youtube",
                                            class: "mod-image" %>
      </a>
      <br><br>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Modevos</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <section>
      <div class="container">
        <div class="row">
          <div class="mod-main col-md-12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/news/_form_create.html.erb
<% if @new.errors.any? %>
<div id='error_explanation'>
  <h2><%= pluralize(@new.errors.count, 'error') %> saved:</h2>

  <ul>
    <% @new.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class='news-bloc' style='text-align: center'>
  <%= form_for @new, url: news_index_path do |f| %>

    <div class='field'>
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form_text' %>
    </div>
    <div class='field'>
      <%= f.label :image %><br>
      <%= image_tag @new.image, class: 'mod-image hidden',
                                id: 'imagePreview'%>
      <%= f.file_field :image, id: 'imageInput' %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class='field'>
      <%= f.label :description %><br>
      <%= f.text_area :description, size: '60x5' %>
    </div>
    <div class='field'>
      <%= f.label :content %><br>
      <%= f.text_area :content,  size: '60x5' %>
    </div>

    <div class="actions">
      <%= f.submit "Créer"%>
    </div>
  <% end %>
</div>
<script>
function readURL(input)
{
  console.log('Hello')
  if (input.files && input.files[0])
  {
    console.log('World')
    var reader = new FileReader();
    reader.onload = function(e)
    {
      $('#imagePreview').attr('src', e.target.result);
    }
    reader.readAsDataURL(input.files[0]);
  }
}

$("#imageInput").change(function()
{
  readURL(this);
  $('#imagePreview').removeClass('hidden')
});
</script>

app/views/news/_form_update.html.erb
<% if @new.errors.any? %>
<div id='error_explanation'>
  <h2><%= pluralize(@new.errors.count, 'error') %> saved:</h2>

  <ul>
    <% @new.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class='news-bloc' style='text-align: center'>
  <%= form_for @new, url: news_path(@new) do |f| %>

    <div class='field'>
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form_text' %>
    </div>
    <div class='field'>
      <%= f.label :image %><br>
      <%= image_tag @new.image, class: 'mod-image',
                                id: 'imagePreview'%>
      <%= f.file_field :image, id: 'imageInput' %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class='field'>
      <%= f.label :description %><br>
      <%= f.text_area :description, size: '60x5' %>
    </div>
    <div class='field'>
      <%= f.label :content %><br>
      <%= f.text_area :content,  size: '60x5' %>
    </div>

    <div class='actions'>
      <%= f.submit 'Modifier'%>
    </div>
  <% end %>
</div>
<script>
function readURL(input)
{
  if (input.files && input.files[0])
  {
    var reader = new FileReader();
    reader.onload = function(e)
    {
      $('#imagePreview').attr('src', e.target.result);
    }
    reader.readAsDataURL(input.files[0]);
  }
}

$("#imageInput").change(function()
{
  readURL(this);
});
</script>

app/views/news/edit.html.erb
<h1>Modifier <%= @new.title %></h1>

<%= render 'form_update' %>

app/views/news/index.html.erb
<div class="modal-header black-border">
  <h1 class="modal-title">Actualité</h1>
</div>

<div class="row">
  <div class="col-md-9">
    <div class="row">
      <% if user_signed_in? %>
        <div class="col-md-6">
          <div class="news-bloc">
            <div>
              <%= link_to (image_tag 'new_news.jpg', alt: "Créer une nouvelle news",
                                       class: "mod-image"), new_news_path %>
            </div>
            <div class="news-line"></div>
            <div>
              <div class="news-title">
                <h4><%= "Créer une nouvelle news"  %></h4>
              </div>
              <div class="news-content">
                <%= "Créer" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% @news.each do |new| %>
        <div class="col-md-6">
          <div class="news-bloc">
            <div>
              <%= link_to (image_tag new.image, alt: "Modevos News Image",
                                       class: "mod-image"), new %>
            </div>
            <div class="news-line"></div>
            <div>
              <div class="news-title">
                <h4><%= new.title %></h4>
              </div>
              <div class="news-content">
                <%= new.description %>
              </div>

              <div class="news-date-border">
                <div class="row news-menu-content">
                  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <%= link_to "Voir plus", new %>
                  </div>

                  <span class="col-lg-8 col-md-8 col-sm-8 col-xs-8 news-date">
                      Modifié le <%= new.updated_at.to_s :short %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= render 'layouts/social_bar' %>
</div>

app/views/news/new.html.erb
<h1>Nouvelle Actualité</h1>

<%= render 'form_create' %>

app/views/news/show.html.erb
<div class="modal-header black-border">
  <h1 class="modal-title"><%= @new.title %></h1>
</div>


<div class="row">
  <div class="col-md-9">
    <div class="news-bloc">
      <div>
        <%= image_tag @new.image, alt: "Modevos News Image",
                                  class: "mod-image" %>
      </div>
      <div class="news-line"></div>
      <div>
        <div class="news-content">
          <%= @new.content %>
        </div>

        <div class="news-date-border">
          <div class="row news-menu-content">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <% if user_signed_in? %>
              <ul class="news-crud">
                <li><%= link_to 'Modifier', edit_news_path(@new) %></li>
                <li><%= link_to 'Suprimer', news_path(@new),
                                method: :delete,
                                data: { confirm: 'Êtes vous sûr?' }%></li>
              </ul>
              <% end %>
            </div>

            <span class="col-lg-8 col-md-8 col-sm-8 col-xs-8 news-date">
                Modifié le <%= @new.updated_at.to_s :short %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/social_bar' %>
</div>